version: '3'
services:
  airflow:
    image: airflow
    ports:
      - 30960:8080
    volumes:
      - ~/.ssh:/root/.ssh
      - ./airflow:/home/airflow
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${http_proxy}
